### ISSUE TITLE
Facing errors to run it in replit

### ISSUE THREAD

**Issue by AIGaming01** [NotSaksh/Hydrox#5]
**My error:**

node index.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/runner/Hydrox/node_modules/discord-together/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/Hydrox/node_modules/discord-together/node_modules/discord.js/src/index.js
- /home/runner/Hydrox/node_modules/discord-together/src/DiscordTogether.js
- /home/runner/Hydrox/node_modules/discord-together/index.js
- /home/runner/Hydrox/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/Hydrox/node_modules/discord-together/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/Hydrox/node_modules/discord-together/node_modules/discord.js/src/index.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/Hydrox/node_modules/discord-together/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/Hydrox/node_modules/discord-together/node_modules/discord.js/src/index.js',
    '/home/runner/Hydrox/node_modules/discord-together/src/DiscordTogether.js',
    '/home/runner/Hydrox/node_modules/discord-together/index.js',
    '/home/runner/Hydrox/index.js'
  ]
}

**Comment by NotSaksh** [comment]
Join Our Discord Server.

**Comment by AIGaming01** [comment]
> Join Our Discord Server.

ok
